<?php

/**
 * @file
 * Small customisations for the Time website.
 */


/*
 * Implements hook_views_post_execute()
 */
function time_misc_views_post_execute( &$view ) {

  switch ( $view->name ) {
  case 'available_jobs' :
    _time_misc_remove_duplicate_nodes( $view );
    break;
  }
}

/**
 * Remove duplicate rows from an executed node view.
 *
 * @param $view
 *   The view object passed to hook_views_post_execute()
 */
function _time_misc_remove_duplicate_nodes( &$view ) {

  $nids_found = array();
  $new_view_result = array();

  foreach ( $view->result as $row )
  {
    // Is this the first time we've seen the filter value of this row?
    if ( ! in_array( $row->nid, $nids_found ) )
    {
      $new_view_result[] = $row;
      $nids_found[] = $row->nid;
    }
  }

  $view->result = $new_view_result;
}
